apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: csye7220-yesno
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: csye7220-yesno
    spec:
      containers:
      - image: prashantkabra/csye7720-backend
        imagePullPolicy: Always
        name: csye7220-yesno
        ports:
        - containerPort: 8080