apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::878060167884:role/terraform-eks-final-project-node
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  #kubectl create configmap my-config --from-literal=API_URL_FROM_CONF=http://40.121.167.36/answer